name: secret key use
on: push
jobs:
  build:
    env:
      AWS_REGION: us-east-1
      CONTAINER_NAME: new-container
    runs-on: ubuntu-latest
    steps:    
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{env.AWS_REGION}}
